credentials:
  usernames:
    admin_mde:
      email: admin@environnement.gov.gn
      name: Administrateur Principal
      password: $2b$12$kZpX0.3Rz9.H/6zGk8/7uO8z5yR8u1.Y1w2e3r4t5y6u7i8o9p0q  # correspond à 'admin123'
      logged_in: False
    agent_conakry:
      email: agent.c@environnement.gov.gn
      name: Agent de Saisie Conakry
      password: $2b$12$L9.H/6zGk8/7uO8z5yR8u1.Y1w2e3r4t5y6u7i8o9p0qZpX0.3Rz9  # correspond à 'agent123'
      logged_in: False

cookie:
  expiry_days: 30
  key: signature_securisee_ministere_guinee  # À modifier pour la production
  name: auth_mde_guinee

preauthorized:
  emails:
    - ministre@environnement.gov.gn
